In [2]:
# Standard Python Notebook Settings
%config IPCompleter.greedy=True
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
from pprint import pprint
import sklearn.datasets
import ipywidgets as widgets
from ipywidgets import interact, interact_manual
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
import pandas as pd 
pd.option_context('display.max_rows', None, 'display.max_columns', None)
import sys
np.set_printoptions(threshold=sys.maxsize)
np.set_printoptions(threshold=np.inf)

Code Source: https://towardsdatascience.com/neural-networks-to-predict-the-market-c4861b649371

Source: https://learndatasci.com/tutorials/python-finance-part-yahoo-finance-api-pandas-matplotlib/

In [3]:
!pip install pandas-datareader

In [0]:
from pandas_datareader import data
import matplotlib.pyplot as plt
import pandas as pd

In [0]:
# Define the instruments to download. We would like to see Microsoft data.
# We would like all available data from 01/01/2010 until 12/31/2019.
start_date = '2010-01-01'
end_date = '2019-12-31'

# User pandas_reader.data.DataReader to load the desired data. As simple as that.
panel_data = data.DataReader('MSFT', 'yahoo', start_date, end_date)

In [33]:
panel_data

High         Low  ...      Volume   Adj Close
Date                                ...                        
2010-01-04   31.100000   30.590000  ...  38409100.0   24.360727
2010-01-05   31.100000   30.639999  ...  49749600.0   24.368599
2010-01-06   31.080000   30.520000  ...  58182400.0   24.219046
2010-01-07   30.700001   30.190001  ...  50559700.0   23.967175
2010-01-08   30.879999   30.240000  ...  51197400.0   24.132469
...                ...         ...  ...         ...         ...
2019-12-24  157.710007  157.119995  ...   8989200.0  157.380005
2019-12-26  158.729996  157.399994  ...  14520600.0  158.669998
2019-12-27  159.550003  158.220001  ...  18412800.0  158.960007
2019-12-30  159.020004  156.729996  ...  16348400.0  157.589996
2019-12-31  157.770004  156.449997  ...  18369400.0  157.699997

[2516 rows x 6 columns]

In [0]:
next_day_opening = panel_data['Open'].iloc[1:2516]

In [35]:
next_day_opening

Date
2010-01-05     30.850000
2010-01-06     30.879999
2010-01-07     30.629999
2010-01-08     30.280001
2010-01-11     30.709999
                 ...    
2019-12-24    157.479996
2019-12-26    157.559998
2019-12-27    159.449997
2019-12-30    158.990005
2019-12-31    156.770004
Name: Open, Length: 2515, dtype: float64

In [0]:
data = panel_data[['High','Low',	'Open',	'Close','Volume','Adj Close']].iloc[0:2515]

In [127]:
data.tail()

High         Low  ...      Volume   Adj Close
Date                                ...                        
2019-12-23  158.119995  157.270004  ...  17718200.0  157.410004
2019-12-24  157.710007  157.119995  ...   8989200.0  157.380005
2019-12-26  158.729996  157.399994  ...  14520600.0  158.669998
2019-12-27  159.550003  158.220001  ...  18412800.0  158.960007
2019-12-30  159.020004  156.729996  ...  16348400.0  157.589996

[5 rows x 6 columns]

In [38]:
next_day_opening

Date
2010-01-05     30.850000
2010-01-06     30.879999
2010-01-07     30.629999
2010-01-08     30.280001
2010-01-11     30.709999
                 ...    
2019-12-24    157.479996
2019-12-26    157.559998
2019-12-27    159.449997
2019-12-30    158.990005
2019-12-31    156.770004
Name: Open, Length: 2515, dtype: float64

In [0]:
data_np = data.to_numpy()

In [0]:
next_np = next_day_opening.to_numpy()

In [41]:
data_np.shape

(2515, 6)

In [42]:
next_np.shape

(2515,)

In [43]:
next_np.reshape(2515,1)

array([[ 30.85000038],
       [ 30.87999916],
       [ 30.62999916],
       ...,
       [159.44999695],
       [158.99000549],
       [156.77000427]])

In [0]:

np.set_printoptions(threshold=50)

stock_data = np.column_stack([data_np,next_np])

In [45]:
np.set_printoptions(suppress=True)
stock_data[1]

array([      31.10000038,       30.63999939,       30.85000038,
             30.95999908, 49749600.        ,       24.36859894,
             30.87999916])

In [46]:
stock_data.shape

(2515, 7)

In [162]:
from sklearn.model_selection import train_test_split
X = stock_data[:,0:2]
y = stock_data[:,6]
print(X[1])
print(y[1])

[31.10000038 30.63999939]
30.8799991607666


In [77]:
X.shape

(2515, 5)

In [78]:
y.shape

(2515,)

In [0]:
#Scale the inputs
from sklearn.preprocessing import StandardScaler
#scalerX = StandardScaler().fit(X)
#y = y.reshape(-1, 1)
#scalery = StandardScaler().fit(y)
#X = scalerX.transform(X)
#y = scalery.transform(y)
#y = np.log(y)

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3, random_state=0)

In [164]:
print(X_train.shape,"\t",y_train.shape,"\n",X_test.shape,"\t",y_test.shape)

(1760, 2) 	 (1760,) 
 (755, 2) 	 (755,)


In [0]:
from keras.callbacks import ModelCheckpoint
from keras.models import Sequential
from keras.layers import Dense, Activation, Flatten
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error 
from matplotlib import pyplot as plt
import seaborn as sb
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import warnings 
warnings.filterwarnings('ignore')
warnings.filterwarnings('ignore', category=DeprecationWarning)
from xgboost import XGBRegressor

In [166]:
NN_model = Sequential()

# The Input Layer :
NN_model.add(Dense(128, kernel_initializer='normal',input_dim = X_train.shape[1], activation='relu'))

# The Hidden Layers :
NN_model.add(Dense(256, kernel_initializer='normal',activation='relu'))
NN_model.add(Dense(256, kernel_initializer='normal',activation='relu'))
NN_model.add(Dense(256, kernel_initializer='normal',activation='relu'))

# The Output Layer :
NN_model.add(Dense(1, kernel_initializer='normal',activation='linear'))

# Compile the network :
NN_model.compile(loss='mean_absolute_error', optimizer='adam', metrics=['mean_absolute_error'])
NN_model.summary()

Model: "sequential_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_51 (Dense)             (None, 128)               384       
_________________________________________________________________
dense_52 (Dense)             (None, 256)               33024     
_________________________________________________________________
dense_53 (Dense)             (None, 256)               65792     
_________________________________________________________________
dense_54 (Dense)             (None, 256)               65792     
_________________________________________________________________
dense_55 (Dense)             (None, 1)                 257       
Total params: 165,249
Trainable params: 165,249
Non-trainable params: 0
_________________________________________________________________


In [0]:
checkpoint_name = 'Weights-{epoch:03d}--{val_loss:.5f}.hdf5' 
checkpoint = ModelCheckpoint(checkpoint_name, monitor='val_loss', verbose = 1, save_best_only = True, mode ='auto')
callbacks_list = [checkpoint]

In [168]:
# Train the model
NN_model.fit(X_train, y_train, epochs=100, batch_size=32, validation_split = 0.2, callbacks=callbacks_list)

Train on 1408 samples, validate on 352 samples
Epoch 1/100
1408/1408 [==============================] - 1s 766us/step - loss: 15.2677 - mean_absolute_error: 15.2677 - val_loss: 1.4016 - val_mean_absolute_error: 1.4016

Epoch 00001: val_loss improved from inf to 1.40162, saving model to Weights-001--1.40162.hdf5
Epoch 2/100
1408/1408 [==============================] - 0s 127us/step - loss: 0.5918 - mean_absolute_error: 0.5918 - val_loss: 0.4574 - val_mean_absolute_error: 0.4574

Epoch 00002: val_loss improved from 1.40162 to 0.45737, saving model to Weights-002--0.45737.hdf5
Epoch 3/100
1408/1408 [==============================] - 0s 122us/step - loss: 0.9376 - mean_absolute_error: 0.9376 - val_loss: 0.5493 - val_mean_absolute_error: 0.5493

Epoch 00003: val_loss did not improve from 0.45737
Epoch 4/100
1408/1408 [==============================] - 0s 127us/step - loss: 0.9723 - mean_absolute_error: 0.9723 - val_loss: 1.0319 - val_mean_absolute_error: 1.0319

Epoch 00004: val_loss did no

In [115]:
!ls -ltr


total 3976
drwxr-xr-x 1 root root    4096 Dec 18 16:52 sample_data
-rw-r--r-- 1 root root 1353824 Jan  8 09:26 Weights-001--0.10046.hdf5
-rw-r--r-- 1 root root 1353824 Jan  8 09:26 Weights-002--0.08434.hdf5
-rw-r--r-- 1 root root 1353824 Jan  8 09:26 Weights-003--0.04438.hdf5


In [0]:
# Load wights file of the best model :
wights_file = 'Weights-016--0.43916.hdf5' # choose the best checkpoint 
NN_model.load_weights(wights_file) # load it
NN_model.compile(loss='mean_absolute_error', optimizer='adam', metrics=['mean_absolute_error'])

In [170]:
NN_model.evaluate(X_test,y_test)

755/755 [==============================] - 1s 1ms/step


[0.36306736161377257, 0.36306736161377257]

In [122]:
X_test[5]

array([1.19457648, 1.21869505, 1.21515125, 1.20900894])

In [0]:
X_new = np.array([159,	156]).reshape(1,-1)
#X_new = scalerX.transform(X_new)	
y_new = NN_model.predict(X_new)

In [173]:
y_new


array([[157.97545]], dtype=float32)